### PR TITLE
Ui table

### PR DESCRIPTION
**Pull request by cfoellmann**
Most UI strings translatable
Split table in two rows to align with dolibarr core style and future field placements

### CODE REVIEW

**Comment by atm-ph** [comment]
Can you show us a screenshot about UI change ?

**Comment by cfoellmann** [comment]
dispatch-before
dispatch-after

Second/red is the AFTER.
The headline for the second table uses `load_fiche_titre()`.
The top details tble is split to make room for info on the right. I plan to display data like the missing comment of the makeorder step

**Comment by cfoellmann** [comment]
If you dont like the change I can revert the last commit and only send the changes for translatable strings

**Comment by cfoellmann** [comment]
@atm-ph should I remove the last commit? Not change the table /not split it

**Comment by atm-ph** [comment]
Sorry for taking long time to answer, I'm agree with UI change

**Comment by cfoellmann** [comment]
do you need feedback from someone else? @atm-ph 
Or should I re-add the commit?

**Comment by cfoellmann** [comment]
@atm-ph just merge the current state.
I will send another PR for the table changes

**Pull request merged**
